"""LLM-backed planner/repair reasoning (proposal §5.2), running against a
local Ollama server instead of a hosted API.

Only two things in the whole storefront ever touch a language model: turning
a free-text agent query into a structured retrieval intent (the Planner
node), and tightening that intent after a schema-validation failure (the
Repair node). Every *factual* field in the final offer -- price, spec,
trust status -- is copied verbatim from the pricing/product/verification
subsystems elsewhere in the graph (see storefront/graph.py's response
composer), never generated here. That split is what proposal §5.4 means by
"numeric and factual fields are never generated by the LLM."

Why Ollama: it's a local inference server (https://ollama.com) -- no API
key, no per-token cost, no network egress once the model is pulled, which
matters for a merchant-side pricing/query system that would rather not send
every agent query to a third-party API. `ollama pull llama3.2` (or any
other model you have pulled) before running this. Ollama's `/api/chat`
endpoint accepts `"format": "json"` and constrains decoding to valid JSON,
which is what makes the planner's output reliably parseable without a
function-calling API.

If `AGENTMARKET_LLM_PROVIDER=none`, or Ollama isn't reachable, or the model
isn't pulled, or a request times out, both functions fall back to a
deterministic heuristic so the rest of the pipeline (and the test suite)
keeps working without a local model running -- useful for CI, not the
intended demo mode.
"""
from __future__ import annotations

import json
import logging
import re

import httpx

from agentmarket_core.config import settings

LLM_ENABLED = settings.llm_enabled
OLLAMA_BASE_URL = settings.ollama_base_url
OLLAMA_MODEL = settings.ollama_model
OLLAMA_TIMEOUT_SECONDS = settings.ollama_timeout_seconds

log = logging.getLogger("agentmarket.llm")

_http = httpx.Client(base_url=OLLAMA_BASE_URL, timeout=OLLAMA_TIMEOUT_SECONDS)

if not LLM_ENABLED:
    log.warning(
        "AGENTMARKET_LLM_PROVIDER=none -- storefront planner/repair nodes will use a "
        "deterministic keyword fallback instead of a real LLM."
    )

PLANNER_SYSTEM_PROMPT = """You are the query-planning node of an AI-agent-facing e-commerce \
storefront. An autonomous shopping agent sends you a free-text request. Decompose it into a \
structured retrieval intent for a downstream semantic search + attribute-filter pipeline.

Respond with ONLY a single JSON object, no prose, no markdown fences, matching this shape:
{
  "search_query": "<short keyword/phrase query for semantic search over product descriptions>",
  "max_price": <number or null>,
  "required_terms": [<0-4 short strings the product description/attributes should satisfy, e.g. "waterproof", "under 500g">]
}"""

REPAIR_SYSTEM_PROMPT = """You are the repair node of an AI-agent-facing e-commerce storefront. \
The previous retrieval attempt failed a strict schema/attribute check. Given the original query \
and the validation error, produce a NARROWER search query likely to retrieve a candidate that \
will pass. Respond with ONLY a single JSON object: {"search_query": "<revised query>"}"""

# The intent decoder's model half. It is allowed to propose predicates only
# from the closed vocabulary below; agentmarket_core.domain.intent discards
# anything else and re-runs its deterministic rules over the raw query
# afterwards, so a bad decode here can widen coverage but never corrupt it.
INTENT_SYSTEM_PROMPT = """You decode shopping requests for a merchant's B2A commerce API. \
An autonomous buying agent relays what its human owner wants, in the owner's own words. Your job \
is to translate stated human outcomes into predicates over product attributes. Do NOT copy \
keywords: map the underlying need. "Never hiked before" is experience_level beginner, not the \
word "never".

Respond with ONLY one JSON object:
{
  "search_query": "<short phrase describing the KIND of product, no pronouns, no budget, no names>",
  "interpreted_need": "<one sentence: what the buyer actually needs>",
  "experience_level": "beginner" | "intermediate" | "expert" | null,
  "use_cases": [<0-4 of: day_hike, multi_day_trek, camping, wet_weather, cold_weather, alpine, first_hike, joint_comfort, knee_support>],
  "values": [<0-4 of: ethical_labour, recycled_materials, repairable, low_carbon_transport, pfc_free, animal_welfare>],
  "budget": <number or null>,
  "bundle_intent": <true if the buyer wants a kit/set of several items, else false>,
  "constraints": [
    {"field": "<one of: experience_level, ease_of_use, break_in_required, weight_g, waterproof_rating, temp_rating_c, comfort_rating_c, use_cases, wide_fit, joint_support, machine_washable, capacity_l, r_value, category, lumens, insulated_hours>",
     "op": "lte" | "gte" | "eq" | "not_eq" | "contains" | "in",
     "value": <number, string or boolean>,
     "kind": "hard" | "soft",
     "source_phrase": "<the exact words from the request that imply this>",
     "rationale": "<why this predicate follows from those words>"}
  ]
}
Use "hard" only for requirements the buyer stated as non-negotiable. Preferences are "soft"."""

# The rationale composer. It is given a fact sheet and may use nothing else;
# every number it writes is checked against that sheet before the text ships
# (see domain/rationale.check_grounding).
RATIONALE_SYSTEM_PROMPT = """You write the justification a merchant's system returns to an \
autonomous buying agent explaining why a product matches its owner's request.

You are given a JSON fact sheet. Rules, enforced by an automated check that will discard your \
text if broken:
1. Use ONLY facts present in the fact sheet. Invent nothing.
2. Every number you write must appear in the fact sheet.
3. Do not describe the product as ethical, sustainable, recycled, durable or low-carbon unless \
that exact claim appears in "verified_claims".
4. No superlatives: never "best", "perfect", "guaranteed", "unbeatable", "top-rated".
5. Mention anything in "requirements_not_met" honestly.

Write 2-4 sentences of plain prose, addressed to the buying agent, explaining how the specific \
requirements were met and citing the evidence. Respond with ONLY a JSON object: \
{"justification": "<your text>"}"""


def is_ollama_available() -> bool:
    """Quick reachability check (short timeout) -- used for the startup/demo
    banner only. The actual plan_query/repair_query calls below re-check by
    just trying the request and falling back on failure, so this is purely
    informational and never gates correctness."""
    if not LLM_ENABLED:
        return False
    try:
        resp = _http.get("/api/tags", timeout=2.0)
        return resp.status_code == 200
    except httpx.HTTPError:
        return False


def _extract_json(text: str) -> dict:
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if not match:
        raise ValueError(f"no JSON object found in LLM output: {text!r}")
    return json.loads(match.group(0))


def _call_ollama(system: str, user: str) -> str:
    resp = _http.post("/api/chat", json={
        "model": OLLAMA_MODEL,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        "stream": False,
        "format": "json",       # constrains Ollama's decoding to valid JSON
        "options": {"temperature": 0},
    })
    resp.raise_for_status()
    body = resp.json()
    return body["message"]["content"]


def _heuristic_plan(query: str) -> dict:
    max_price = None
    m = re.search(r"under\s*\$?(\d+(?:\.\d+)?)", query, re.IGNORECASE)
    if m:
        max_price = float(m.group(1))
    terms = [w for w in re.findall(r"[a-zA-Z]{4,}", query)][:4]
    return {"search_query": query, "max_price": max_price, "required_terms": terms}


def plan_query(query: str) -> dict:
    """Returns {"search_query": str, "max_price": float|None, "required_terms": [str]}."""
    if not LLM_ENABLED:
        return _heuristic_plan(query)
    try:
        text = _call_ollama(PLANNER_SYSTEM_PROMPT, query)
        parsed = _extract_json(text)
        return {
            "search_query": parsed.get("search_query") or query,
            "max_price": parsed.get("max_price"),
            "required_terms": parsed.get("required_terms") or [],
        }
    except (httpx.HTTPError, ValueError, KeyError, json.JSONDecodeError) as exc:
        log.warning(
            "Ollama planner call failed (%s) -- is `ollama serve` running and has "
            "`ollama pull %s` been run? Falling back to heuristic.", exc, OLLAMA_MODEL,
        )
        return _heuristic_plan(query)


def decode_intent(query: str) -> dict | None:
    """Ask the model for a structured decode. Returns None when unavailable.

    None rather than a guess: the caller's rule layer is a complete decoder on
    its own, so "no model" and "an empty decode" must not look the same.
    """
    if not LLM_ENABLED:
        return None
    try:
        parsed = _extract_json(_call_ollama(INTENT_SYSTEM_PROMPT, query))
    except (httpx.HTTPError, ValueError, KeyError, json.JSONDecodeError) as exc:
        log.warning("Ollama intent decode failed (%s); using deterministic rules only", exc)
        return None
    if not isinstance(parsed, dict):
        return None
    return parsed


def compose_rationale(fact_sheet: dict) -> str:
    """Write the justification from a fact sheet. Empty string if unavailable.

    The caller treats an empty return as "use the template", and checks
    whatever is returned against the fact sheet before shipping it.
    """
    if not LLM_ENABLED:
        return ""
    try:
        payload = json.dumps(fact_sheet, default=str)[:6000]
        parsed = _extract_json(_call_ollama(RATIONALE_SYSTEM_PROMPT, payload))
        return str(parsed.get("justification") or "").strip()
    except (httpx.HTTPError, ValueError, KeyError, json.JSONDecodeError) as exc:
        log.warning("Ollama rationale composition failed (%s); using template", exc)
        return ""


def repair_query(original_query: str, error: str) -> str:
    if not LLM_ENABLED:
        return original_query  # nothing smarter to do without a model
    try:
        user = f"Original query: {original_query!r}\nValidation error: {error}"
        text = _call_ollama(REPAIR_SYSTEM_PROMPT, user)
        parsed = _extract_json(text)
        return parsed.get("search_query") or original_query
    except (httpx.HTTPError, ValueError, KeyError, json.JSONDecodeError) as exc:
        log.warning("Ollama repair call failed (%s); reusing original query", exc)
        return original_query
